name: flaticon
description: "This resource is from flaticon."
version: 1.0.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: bold-rounded
      fonts:
        - asset: assets/fonts/bold-rounded.woff
        - asset: assets/fonts/bold-rounded.woff2
    - family: bold-straight
      fonts:
        - asset: assets/fonts/bold-straight.woff
        - asset: assets/fonts/bold-straight.woff2
    - family: regular-chubby
      fonts:
        - asset: assets/fonts/regular-chubby.woff
        - asset: assets/fonts/regular-chubby.woff2
    - family: regular-rounded
      fonts:
        - asset: assets/fonts/regular-rounded.woff
        - asset: assets/fonts/regular-rounded.woff2
    - family: regular-straight
      fonts:
        - asset: assets/fonts/regular-straight.woff
        - asset: assets/fonts/regular-straight.woff2
    - family: solid-chubby
      fonts:
        - asset: assets/fonts/solid-chubby.woff
        - asset: assets/fonts/solid-chubby.woff2
    - family: solid-rounded
      fonts:
        - asset: assets/fonts/solid-rounded.woff
        - asset: assets/fonts/solid-rounded.woff2
    - family: solid-straight
      fonts:
        - asset: assets/fonts/solid-straight.woff
        - asset: assets/fonts/solid-straight.woff2
    - family: thin-chubby
      fonts:
        - asset: assets/fonts/thin-chubby.woff
        - asset: assets/fonts/thin-chubby.woff2
    - family: thin-rounded
      fonts:
        - asset: assets/fonts/thin-rounded.woff
        - asset: assets/fonts/thin-rounded.woff2
    - family: thin-straight
      fonts:
        - asset: assets/fonts/thin-straight.woff
        - asset: assets/fonts/thin-straight.woff2
  module:
    androidX: true
    androidPackage: com.tnoud.flaticon
    iosBundleIdentifier: com.tnoud.flaticon
